// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_IPT4VvxNlxw38b0v3C2CM8m6i-zdEew',
    appId: '1:1069438088848:web:679ab4455cbca428df0a15',
    messagingSenderId: '1069438088848',
    projectId: 'signuplogin-ddf0f',
    authDomain: 'signuplogin-ddf0f.firebaseapp.com',
    storageBucket: 'signuplogin-ddf0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMeEQ7ugGL4F93MtqycmxNR7Zpt7ovo5U',
    appId: '1:1069438088848:android:6840344aae574c8adf0a15',
    messagingSenderId: '1069438088848',
    projectId: 'signuplogin-ddf0f',
    storageBucket: 'signuplogin-ddf0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAovNuPcdDgvviFLMS-ffYbxnwyCkhjI50',
    appId: '1:1069438088848:ios:0363f2e3cb50bf6adf0a15',
    messagingSenderId: '1069438088848',
    projectId: 'signuplogin-ddf0f',
    storageBucket: 'signuplogin-ddf0f.appspot.com',
    iosClientId: '1069438088848-umqq15sp0s6vo0vgvldkgjse8e05b9p0.apps.googleusercontent.com',
    iosBundleId: 'com.example.signupLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAovNuPcdDgvviFLMS-ffYbxnwyCkhjI50',
    appId: '1:1069438088848:ios:0363f2e3cb50bf6adf0a15',
    messagingSenderId: '1069438088848',
    projectId: 'signuplogin-ddf0f',
    storageBucket: 'signuplogin-ddf0f.appspot.com',
    iosClientId: '1069438088848-umqq15sp0s6vo0vgvldkgjse8e05b9p0.apps.googleusercontent.com',
    iosBundleId: 'com.example.signupLogin',
  );
}
